language: node_js
node_js:
  - "lts/*"
script:
  - npm run build
  - rm _book/**/*.md
  - rm -rf _book/gitbook/images
  - cp -R book/assets/images _book/gitbook
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _book
  project-name: "WebPurple Learn Book"
  on:
    branch: master
