language: node_js
node_js:
  - "lts/*"
script:
  - npm run build
  - rm _book/TAGS.md
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _book
  project-name: "WebPurple Learn Book"
  on:
    branch: master
